BEGIN;
DROP TABLE IF EXISTS stations;
DROP TABLE IF EXISTS time_values;
DROP TABLE IF EXISTS level_values;
DROP TABLE IF EXISTS tide_values;
DROP TABLE IF EXISTS station_values;
DROP TABLE IF EXISTS level_station_values;
DROP TABLE IF EXISTS tide_station_values;
DROP TABLE IF EXISTS temptimecsv;
DROP TABLE IF EXISTS temptidecsv;
DROP TABLE IF EXISTS tempstationcsv;
COMMIT;
